name: Setup poetry
description: Setup poetry according to .tool-versions

inputs:
  aws-access-key-id:
    description: AWS access key ID
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true


runs:
  using: "composite"
  steps:
    - name: Get tool versions
      run: |
        set -x
        echo "PYTHON_VERSION=$(cat .tool-versions | perl -ne 'print $1 if /^python (.*?)$/')" >> $GITHUB_ENV
        echo "POETRY_VERSION=$(cat .tool-versions | perl -ne 'print $1 if /^poetry (.*?)$/')" >> $GITHUB_ENV
      shell: bash
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install poetry
      run: pip install poetry==${{ env.POETRY_VERSION }}
      shell: bash
    - name: Cache poetry cache
      uses: actions/cache@v4
      if: ${{ inputs.working-directory != '.' }}
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles(format('{0}/**/poetry.lock', inputs.working-directory)) }}
        restore-keys: ${{ runner.os }}-poetry-
