name: Update renovate PR

on:
  push:
    branches:
      - 'renovate/*'
    paths:
      - 'lambda/poetry.lock'
  workflow_dispatch:

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup poetry
        uses: ./.github/actions/setup-poetry
        with:
          working-directory: lambda
      - name: Configure git
        run: |
          git config --global user.name "Tomohiko Ozawa"
          git config --global user.email "kota65535@gmail.com"
      - name: Run pre-commit hook script
        run: ./pre-commit.sh
      - name: Commit & push
        run: |
          git add .
          git commit --amend --no-edit
          git push -f origin HEAD
